title: "Ange Chierchia"
tagline: "Développeur Web full-stack"
email: ange.chierchia@gmail.com
author: 'Ange Chierchia'
description: > # this means to ignore newlines until "baseurl:"
  Développeur Web full-stack à Luxembourg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chierchia.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nighcrawl
github_username:  nighcrawl

opengraph_visual: '/assets/img/opengraph.jpg'
rss_thumbnail: '/assets/img/feed-default-thumbnail.jpg'

placeholder: "/assets/img/placeholder.png"

permalink: /blog/:year/:month/:title

include:
  - _pages

paginate: 10
paginate_path: "/blog/page/:num/"

sass:
    style: compressed
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-minimal