title: "Ange Chierchia"
tagline: "Développeur Web full-stack"
timezone: Europe/Paris
email: ange.chierchia@gmail.com
author: 'Ange Chierchia'
description: > # this means to ignore newlines until "baseurl:"
  Développeur Web full-stack à Luxembourg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chierchia.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nighcrawl
github_username:  nighcrawl

opengraph_visual: '/assets/img/opengraph.jpg'
rss_thumbnail: '/assets/img/feed-default-thumbnail.jpg'

placeholder: "/assets/img/placeholder.png"

permalink: /blog/:year/:month/:title

include:
  - _pages
  - .well-known

paginate: 10
paginate_path: "/blog/page/:num/"

sass:
    style: compressed
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-minimal

collections:
  posts:
    syndicate_to: [ mastodon ]
  category:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "archives-category"
webmentions:
  username: chierchia.fr
  cache_folder: .cache
  legacy_domains:
    - http://blog.angechierchia.com
    - http://chierchia.fr
  max_attempts: 5
  bad_uri_policy:
    unsupported:
      policy: ban
    error:
      policy: ignore
    failure:
      policy: retry
      retry_delay: [ 1, 12, 48, 120 ]
      max_retries: 5
    whitelist:
      - "^https://brid.gy/publish/"
  syndication:
    mastodon: 
      endpoint: https://brid.gy/publish/mastodon
      response_mapping:
        syndication: $.url
