title: "Ange Chierchia"
tagline: "Webdesigner & développeur full-stack"
email: ange.chierchia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Webdesigner & développeur full-stack à Luxembourg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nighcrawl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nighcrawl
github_username:  nighcrawl

paginate: 10
paginate_path: "/blog/page/:num/"

sass:
    style: compressed
markdown: kramdown

gems:
  - jekyll-paginate
