backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
site_url: https://chierchia.fr
display_url: https://chierchia.fr
publish_mode: editorial_workflow
media_folder: 'contents/uploads'
slug:
  encoding: unicode
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    preview_path: blog/{{year}}/{{month}}/{{title}}
    preview_path_date_field: date
    sort: "updated_on:desc"
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - label: "Categories"
        name: "categories" 
        widget: "select"
        multiple: true
        options:
          - {value: 'Font-End', label: 'Front-End'}
          - {value: 'Back-End', label: 'Back-End'}
          - {value: 'Ressource', label: 'Ressource'}
          - {value: 'Vis ma vie', label: 'Vis ma vie'}
      - {label: "Tags", name: "tags", widget: "list", default: ["tweet"], required: false}
      - {label: "Post Format", name: "format", widget: "select", options: ['post', 'link', 'status'], default: ['post'], required: false}
      - {label: "URL to Share", name: 'link', widget: 'string', required: false, pattern: ['^https?:\/\/', 'Must start with http:// or https://']}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Share online", name: "publish_social", widget: "select", options: ['yes', 'no'], default: ['yes'], required: true}
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    sort: "title:asc"
    editor:
      preview: false
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Featured Image CSS Class", name: "image_class", widget: "string", required: false}
      - {label: "Permalink", name: 'permalink', widget: "string", required: false}
      - {label: "Body CSS class", name: 'body_class', widget: 'string', required: false}
      - {label: "Body", name: "body", widget: "markdown"}