backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
site_url: https://chierchia.fr
display_url: https://chierchia.fr
publish_mode: editorial_workflow
media_folder: 'contents/uploads'
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    sort: "updated_on:desc"
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "blog/{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - label: "Categories"
        name: "categories" 
        widget: "select"
        multiple: true
        options:
          - {value: 'Font-End', label: 'Front-End'}
          - {value: 'Back-End', label: 'Back-End'}
          - {value: 'Ressource', label: 'Ressource'}
          - {value: 'Vis ma vie', label: 'Vis ma vie'}
      - {label: "Tags", name: "tags", widget: "list", default: ["tweet"], required: false}
      - {label: "Post Format", name: "format", widget: "select", options: ['post', 'link', 'status'], default: ['post'], required: false}
      - {label: "Permalink", name: "permalink", widget: "string", default: '/blog/{{slug}}'}
      - {label: "Body", name: "body", widget: "markdown"}